apiVersion: apps/v1
kind: Deployment
metadata:
  name: apro-matching-engine
  namespace: kong
spec:
  strategy:
    type: RollingUpdate
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: apro-matching-engine
  template:
    metadata:
      labels:
        app: apro-matching-engine
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi
      nodeSelector:
        group: apro-exchange-main-general
        'karpenter-created': "true"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - apro-matching-engine
              topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: DoNotSchedule
        minDomains: 2
        labelSelector:
          matchLabels:
            app: apro-matching-engine
        matchLabelKeys:
        - pod-template-hash